version: "2"

services:
  sonarqube:
    image: sonarqube
    restart: always
    ports:
      - "8888:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=yourpasswordhere
    volumes:
      - /opt/sonarqube/conf:/opt/sonarqube/conf
      - /opt/sonarqube/data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    links:
      - db

  db:
    image: mysql:5.6.34
    restart: always
    networks:
      - sonarnet
    environment:
      - MYSQL_ROOT_PASSWORD=yourpasswordhere
    volumes:
      - /var/lib/mysql:/var/lib/mysql
networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
